#!/usr/bin/env python3
"""Generate help-site ROS graph assets with rqt_graph's dotcode generator."""

import argparse
import subprocess
from pathlib import Path

import rosgraph.impl.graph
import rospy
from qt_dotgraph.pydotfactory import PydotFactory
from rqt_graph.dotcode import (
    NODE_NODE_GRAPH,
    NODE_TOPIC_ALL_GRAPH,
    NODE_TOPIC_GRAPH,
    RosGraphDotcodeGenerator,
)


GRAPH_MODES = {
    "nodes": NODE_NODE_GRAPH,
    "node_topic": NODE_TOPIC_GRAPH,
    "node_topic_all": NODE_TOPIC_ALL_GRAPH,
}


def generate_dotcode(args):
    rospy.init_node(
        "tie_robot_help_rqt_rosgraph_generator",
        anonymous=True,
        disable_signals=True,
    )

    graph = rosgraph.impl.graph.Graph()
    graph.set_master_stale(args.master_stale_sec)
    graph.set_node_stale(args.node_stale_sec)
    graph.update()

    generator = RosGraphDotcodeGenerator()
    dotcode = generator.generate_dotcode(
        rosgraphinst=graph,
        ns_filter=args.namespace_filter,
        topic_filter=args.topic_filter,
        graph_mode=GRAPH_MODES[args.graph_mode],
        dotcode_factory=PydotFactory(),
        hide_single_connection_topics=args.hide_single_connection_topics,
        hide_dead_end_topics=args.hide_dead_end_topics,
        cluster_namespaces_level=args.cluster_namespaces_level,
        accumulate_actions=args.accumulate_actions,
        orientation="LR",
        quiet=args.quiet,
        unreachable=args.unreachable,
        group_tf_nodes=args.group_tf_nodes,
        hide_tf_nodes=args.hide_tf_nodes,
        group_image_nodes=args.group_image_nodes,
        hide_dynamic_reconfigure=args.hide_dynamic_reconfigure,
    )

    header = "\n".join(
        [
            "// Generated by rqt_graph.dotcode.RosGraphDotcodeGenerator.",
            f"// graph_mode={args.graph_mode}",
            f"// namespace_filter={args.namespace_filter}",
            f"// topic_filter={args.topic_filter}",
        ]
    )
    return f"{header}\n{dotcode}"


def run_dot(dot_path, svg_path, png_path):
    subprocess.run(["dot", "-Tsvg", str(dot_path), "-o", str(svg_path)], check=True)
    subprocess.run(
        ["dot", "-Tpng", "-Gdpi=170", str(dot_path), "-o", str(png_path)],
        check=True,
    )


def add_bool_argument(parser, name, default, help_text):
    parser.add_argument(
        f"--{name}",
        dest=name.replace("-", "_"),
        action="store_true",
        help=help_text,
    )
    parser.add_argument(
        f"--no-{name}",
        dest=name.replace("-", "_"),
        action="store_false",
        help=argparse.SUPPRESS,
    )
    parser.set_defaults(**{name.replace("-", "_"): default})


def parse_args():
    parser = argparse.ArgumentParser(
        description="Generate rqt_graph-style ROS graph assets for Tie Robot Help.",
    )
    default_output_dir = (
        Path(__file__).resolve().parents[1]
        / "public"
        / "images"
        / "architecture"
    )
    parser.add_argument("--output-dir", type=Path, default=default_output_dir)
    parser.add_argument("--basename", default="tie-robot-ros-graph")
    parser.add_argument(
        "--graph-mode",
        choices=sorted(GRAPH_MODES.keys()),
        default="node_topic",
        help="rqt_graph graph mode. node_topic matches Nodes/Topics (active).",
    )
    parser.add_argument("--namespace-filter", default="/")
    parser.add_argument("--topic-filter", default="/")
    parser.add_argument("--master-stale-sec", type=float, default=5.0)
    parser.add_argument("--node-stale-sec", type=float, default=5.0)
    parser.add_argument("--cluster-namespaces-level", type=int, default=1)
    add_bool_argument(parser, "quiet", True, "Enable rqt_graph quiet filtering.")
    add_bool_argument(parser, "unreachable", True, "Hide unreachable nodes.")
    add_bool_argument(parser, "accumulate-actions", True, "Group actionlib topics.")
    add_bool_argument(
        parser,
        "hide-single-connection-topics",
        True,
        "Hide leaf topics with a single connection.",
    )
    add_bool_argument(
        parser,
        "hide-dead-end-topics",
        True,
        "Hide topics that only have publishers.",
    )
    add_bool_argument(parser, "group-tf-nodes", True, "Group TF topics.")
    add_bool_argument(parser, "hide-tf-nodes", False, "Hide TF nodes.")
    add_bool_argument(parser, "group-image-nodes", True, "Group image topics.")
    add_bool_argument(
        parser,
        "hide-dynamic-reconfigure",
        True,
        "Hide dynamic_reconfigure plumbing.",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    args.output_dir.mkdir(parents=True, exist_ok=True)

    dot_path = args.output_dir / f"{args.basename}.dot"
    svg_path = args.output_dir / f"{args.basename}.svg"
    png_path = args.output_dir / f"{args.basename}.png"

    dot_path.write_text(generate_dotcode(args), encoding="utf-8")
    run_dot(dot_path, svg_path, png_path)

    print(f"wrote {dot_path}")
    print(f"wrote {svg_path}")
    print(f"wrote {png_path}")


if __name__ == "__main__":
    main()
