uint16 bind_group_point_count
float32 bind_group_row_threshold_mm
float32 bind_group_column_threshold_mm
float32 bind_execution_cabin_min_z_mm
uint8 BIND_EXECUTION_CABIN_Z_MODE_FIXED=0
uint8 BIND_EXECUTION_CABIN_Z_MODE_MIN=1
uint8 bind_execution_cabin_z_mode
uint16 recognition_pose_index
---
bool success
string message
uint32 area_count
uint32 group_count
uint32 point_count
