string command
float64 home_x_mm
float64 home_y_mm
float64 home_z_mm
---
bool success
string message
bool has_current_pose
float64 current_x_mm
float64 current_y_mm
float64 current_z_mm
float64 home_x_mm
float64 home_y_mm
float64 home_z_mm
float64 base_to_camera_x_mm
float64 base_to_camera_y_mm
float64 base_to_camera_z_mm
float64 base_to_camera_roll_rad
float64 base_to_camera_pitch_rad
float64 base_to_camera_yaw_rad
bool has_camera_pose
float64 camera_x_mm
float64 camera_y_mm
float64 camera_z_mm
bool has_ground_probe
float64 camera_ground_distance_mm
float64 ground_x_mm
float64 ground_y_mm
float64 ground_z_mm
