uint8 SCAN_STRATEGY_SINGLE_CENTER=0
uint8 SCAN_STRATEGY_MULTI_POSE=1
uint8 SCAN_STRATEGY_FIXED_MANUAL_WORKSPACE=2
uint8 SCAN_STRATEGY_CURRENT_FRAME_NO_MOTION=3
bool enable_capture_gate
uint8 scan_strategy
uint16 recognition_pose_index
bool use_fixed_scan_pose_override
float32 fixed_scan_pose_x_mm
float32 fixed_scan_pose_y_mm
float32 fixed_scan_pose_z_mm
uint16 bind_group_point_count
float32 bind_group_row_threshold_mm
float32 bind_group_column_threshold_mm
float32 bind_execution_cabin_min_z_mm
uint8 BIND_EXECUTION_CABIN_Z_MODE_FIXED=0
uint8 BIND_EXECUTION_CABIN_Z_MODE_MIN=1
uint8 bind_execution_cabin_z_mode
---
bool success
string message
