#include "tie_robot_control/moduan/runtime_state.hpp"

modbus_t* plc = nullptr;
bool light_state = false;
std::atomic<bool> error_detected(false);
std::mutex error_msg_mutex;
std::string last_error_msg;

tie_robot_msgs::motion transform_msg;
tie_robot_msgs::linear_module_upload linear_module_data_upload;
tie_robot_msgs::ProcessImage srv;
ros::ServiceClient AI_client;
ros::ServiceClient linear_client;
std_srvs::Trigger Trigger_srv;
ros::ServiceClient trigger_client;

double left_motor_speed = 0;
double right_motor_speed = 0;
double gain_speed = 0;
int channel1_percent = 0;
int channel2_percent = 0;
int channel3_percent = 0;
int state = 0;
int send_odd_points = 3;
int fd = -1;
uint8_t data = 0;
ros::Publisher pub_ctl_vel;
ros::Publisher pub_wheel_direction;
std_msgs::Int32 msg_state;
std_msgs::Float32 msg_vel;
uint16_t UtoF_Register[2] = {0, 0};
uint16_t DtoU_Register[2] = {0, 0};
uint16_t UtoD_Register[2] = {0, 0};
uint16_t last_JULI = 0;
double module_speed = 250;
double motor_speed = 360;
double current_z = 0;
bool current_z_flag = false;
std_msgs::Int32 msg;
double reset_angle = 0;
double last_left_motor_speed = 0;
double last_right_motor_speed = 0;
ros::Publisher pub_motor_theata;
ros::Publisher pub_linear_module_gb_origin;
ros::Publisher pub_forced_stop;
ros::Publisher pub_moduan_warning;
ros::Publisher pub_lashing_warning;
ros::Publisher pub_moduan_work;
ros::Publisher pub_moduan_state_topic;
ros::Publisher pub_pause;
ros::Publisher pub_linear_module_data_upload;
int pause_interrupt = 0;
std::mutex module_state_mutex;
std::mutex plc_mutex;
uint16_t MODULE = 0;
Module_State module_state{};
Motor_State motor_state{};
bool enable_lashing = true;
std::mutex lashing_mutex;
ros::Subscriber enb_las_sub;
int pause_interrupt_count = 0;
bool handle_pause_interrupt = false;
std::pair<std::vector<int>, std::vector<float>> bind_data;
std::vector<std::pair<std::vector<int>, std::vector<float>>> bind_all_data;
std::unique_ptr<tie_robot_hw::driver::LinearModuleDriver> g_linear_module_driver;
std::atomic<bool> g_moduan_driver_enabled(true);
std::atomic<bool> g_use_remote_moduan_driver(false);
std::atomic<bool> moduan_plc_execution_state(false);
float last_x = 0.0f;
float last_y = 0.0f;
