// Generated by gencpp from file chassis_ctrl/cabin_calibration.msg
// DO NOT EDIT!


#ifndef CHASSIS_CTRL_MESSAGE_CABIN_CALIBRATION_H
#define CHASSIS_CTRL_MESSAGE_CABIN_CALIBRATION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace chassis_ctrl
{
template <class ContainerAllocator>
struct cabin_calibration_
{
  typedef cabin_calibration_<ContainerAllocator> Type;

  cabin_calibration_()
    : X_height_min(0.0)
    , Y_height_min(0.0)  {
    }
  cabin_calibration_(const ContainerAllocator& _alloc)
    : X_height_min(0.0)
    , Y_height_min(0.0)  {
  (void)_alloc;
    }



   typedef double _X_height_min_type;
  _X_height_min_type X_height_min;

   typedef double _Y_height_min_type;
  _Y_height_min_type Y_height_min;





  typedef boost::shared_ptr< ::chassis_ctrl::cabin_calibration_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chassis_ctrl::cabin_calibration_<ContainerAllocator> const> ConstPtr;

}; // struct cabin_calibration_

typedef ::chassis_ctrl::cabin_calibration_<std::allocator<void> > cabin_calibration;

typedef boost::shared_ptr< ::chassis_ctrl::cabin_calibration > cabin_calibrationPtr;
typedef boost::shared_ptr< ::chassis_ctrl::cabin_calibration const> cabin_calibrationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chassis_ctrl::cabin_calibration_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chassis_ctrl::cabin_calibration_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::chassis_ctrl::cabin_calibration_<ContainerAllocator1> & lhs, const ::chassis_ctrl::cabin_calibration_<ContainerAllocator2> & rhs)
{
  return lhs.X_height_min == rhs.X_height_min &&
    lhs.Y_height_min == rhs.Y_height_min;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::chassis_ctrl::cabin_calibration_<ContainerAllocator1> & lhs, const ::chassis_ctrl::cabin_calibration_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace chassis_ctrl

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::chassis_ctrl::cabin_calibration_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chassis_ctrl::cabin_calibration_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chassis_ctrl::cabin_calibration_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chassis_ctrl::cabin_calibration_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chassis_ctrl::cabin_calibration_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chassis_ctrl::cabin_calibration_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chassis_ctrl::cabin_calibration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9cf180d2bb3eeef6bfe77dc52e5f90b7";
  }

  static const char* value(const ::chassis_ctrl::cabin_calibration_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9cf180d2bb3eeef6ULL;
  static const uint64_t static_value2 = 0xbfe77dc52e5f90b7ULL;
};

template<class ContainerAllocator>
struct DataType< ::chassis_ctrl::cabin_calibration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chassis_ctrl/cabin_calibration";
  }

  static const char* value(const ::chassis_ctrl::cabin_calibration_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chassis_ctrl::cabin_calibration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#这个msg是对索驱整板钢筋的标定，即索驱控制机器人走到整版钢筋最低点，自适应调节自身高度\n"
"float64 X_height_min\n"
"float64 Y_height_min\n"
;
  }

  static const char* value(const ::chassis_ctrl::cabin_calibration_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chassis_ctrl::cabin_calibration_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.X_height_min);
      stream.next(m.Y_height_min);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cabin_calibration_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chassis_ctrl::cabin_calibration_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::chassis_ctrl::cabin_calibration_<ContainerAllocator>& v)
  {
    s << indent << "X_height_min: ";
    Printer<double>::stream(s, indent + "  ", v.X_height_min);
    s << indent << "Y_height_min: ";
    Printer<double>::stream(s, indent + "  ", v.Y_height_min);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CHASSIS_CTRL_MESSAGE_CABIN_CALIBRATION_H
