// Generated by gencpp from file chassis_ctrl/cabin_move_all.msg
// DO NOT EDIT!


#ifndef CHASSIS_CTRL_MESSAGE_CABIN_MOVE_ALL_H
#define CHASSIS_CTRL_MESSAGE_CABIN_MOVE_ALL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace chassis_ctrl
{
template <class ContainerAllocator>
struct cabin_move_all_
{
  typedef cabin_move_all_<ContainerAllocator> Type;

  cabin_move_all_()
    : cabin_X_distance(0.0)
    , cabin_Y_distance(0.0)
    , cabin_Z_distance(0.0)  {
    }
  cabin_move_all_(const ContainerAllocator& _alloc)
    : cabin_X_distance(0.0)
    , cabin_Y_distance(0.0)
    , cabin_Z_distance(0.0)  {
  (void)_alloc;
    }



   typedef double _cabin_X_distance_type;
  _cabin_X_distance_type cabin_X_distance;

   typedef double _cabin_Y_distance_type;
  _cabin_Y_distance_type cabin_Y_distance;

   typedef double _cabin_Z_distance_type;
  _cabin_Z_distance_type cabin_Z_distance;





  typedef boost::shared_ptr< ::chassis_ctrl::cabin_move_all_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chassis_ctrl::cabin_move_all_<ContainerAllocator> const> ConstPtr;

}; // struct cabin_move_all_

typedef ::chassis_ctrl::cabin_move_all_<std::allocator<void> > cabin_move_all;

typedef boost::shared_ptr< ::chassis_ctrl::cabin_move_all > cabin_move_allPtr;
typedef boost::shared_ptr< ::chassis_ctrl::cabin_move_all const> cabin_move_allConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chassis_ctrl::cabin_move_all_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chassis_ctrl::cabin_move_all_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::chassis_ctrl::cabin_move_all_<ContainerAllocator1> & lhs, const ::chassis_ctrl::cabin_move_all_<ContainerAllocator2> & rhs)
{
  return lhs.cabin_X_distance == rhs.cabin_X_distance &&
    lhs.cabin_Y_distance == rhs.cabin_Y_distance &&
    lhs.cabin_Z_distance == rhs.cabin_Z_distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::chassis_ctrl::cabin_move_all_<ContainerAllocator1> & lhs, const ::chassis_ctrl::cabin_move_all_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace chassis_ctrl

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::chassis_ctrl::cabin_move_all_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chassis_ctrl::cabin_move_all_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chassis_ctrl::cabin_move_all_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chassis_ctrl::cabin_move_all_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chassis_ctrl::cabin_move_all_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chassis_ctrl::cabin_move_all_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chassis_ctrl::cabin_move_all_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7347eccc4c34dc920b0ab11854c27b99";
  }

  static const char* value(const ::chassis_ctrl::cabin_move_all_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7347eccc4c34dc92ULL;
  static const uint64_t static_value2 = 0x0b0ab11854c27b99ULL;
};

template<class ContainerAllocator>
struct DataType< ::chassis_ctrl::cabin_move_all_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chassis_ctrl/cabin_move_all";
  }

  static const char* value(const ::chassis_ctrl::cabin_move_all_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chassis_ctrl::cabin_move_all_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 这个msg为了触索驱三轴运动的回调函数\n"
"float64 cabin_X_distance\n"
"float64 cabin_Y_distance\n"
"float64 cabin_Z_distance\n"
;
  }

  static const char* value(const ::chassis_ctrl::cabin_move_all_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chassis_ctrl::cabin_move_all_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cabin_X_distance);
      stream.next(m.cabin_Y_distance);
      stream.next(m.cabin_Z_distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cabin_move_all_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chassis_ctrl::cabin_move_all_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::chassis_ctrl::cabin_move_all_<ContainerAllocator>& v)
  {
    s << indent << "cabin_X_distance: ";
    Printer<double>::stream(s, indent + "  ", v.cabin_X_distance);
    s << indent << "cabin_Y_distance: ";
    Printer<double>::stream(s, indent + "  ", v.cabin_Y_distance);
    s << indent << "cabin_Z_distance: ";
    Printer<double>::stream(s, indent + "  ", v.cabin_Z_distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CHASSIS_CTRL_MESSAGE_CABIN_MOVE_ALL_H
