// Generated by gencpp from file chassis_ctrl/cabin_upload.msg
// DO NOT EDIT!


#ifndef CHASSIS_CTRL_MESSAGE_CABIN_UPLOAD_H
#define CHASSIS_CTRL_MESSAGE_CABIN_UPLOAD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace chassis_ctrl
{
template <class ContainerAllocator>
struct cabin_upload_
{
  typedef cabin_upload_<ContainerAllocator> Type;

  cabin_upload_()
    : cabin_state_X(0.0)
    , cabin_state_Y(0.0)
    , cabin_state_Z(0.0)
    , cabin_state_speed(0.0)
    , motion_status(0)
    , internal_calc_error(0)
    , device_alarm(0)
    , cabin_connect_flag(0)  {
    }
  cabin_upload_(const ContainerAllocator& _alloc)
    : cabin_state_X(0.0)
    , cabin_state_Y(0.0)
    , cabin_state_Z(0.0)
    , cabin_state_speed(0.0)
    , motion_status(0)
    , internal_calc_error(0)
    , device_alarm(0)
    , cabin_connect_flag(0)  {
  (void)_alloc;
    }



   typedef double _cabin_state_X_type;
  _cabin_state_X_type cabin_state_X;

   typedef double _cabin_state_Y_type;
  _cabin_state_Y_type cabin_state_Y;

   typedef double _cabin_state_Z_type;
  _cabin_state_Z_type cabin_state_Z;

   typedef double _cabin_state_speed_type;
  _cabin_state_speed_type cabin_state_speed;

   typedef int32_t _motion_status_type;
  _motion_status_type motion_status;

   typedef int32_t _internal_calc_error_type;
  _internal_calc_error_type internal_calc_error;

   typedef int32_t _device_alarm_type;
  _device_alarm_type device_alarm;

   typedef int32_t _cabin_connect_flag_type;
  _cabin_connect_flag_type cabin_connect_flag;





  typedef boost::shared_ptr< ::chassis_ctrl::cabin_upload_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chassis_ctrl::cabin_upload_<ContainerAllocator> const> ConstPtr;

}; // struct cabin_upload_

typedef ::chassis_ctrl::cabin_upload_<std::allocator<void> > cabin_upload;

typedef boost::shared_ptr< ::chassis_ctrl::cabin_upload > cabin_uploadPtr;
typedef boost::shared_ptr< ::chassis_ctrl::cabin_upload const> cabin_uploadConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chassis_ctrl::cabin_upload_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chassis_ctrl::cabin_upload_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::chassis_ctrl::cabin_upload_<ContainerAllocator1> & lhs, const ::chassis_ctrl::cabin_upload_<ContainerAllocator2> & rhs)
{
  return lhs.cabin_state_X == rhs.cabin_state_X &&
    lhs.cabin_state_Y == rhs.cabin_state_Y &&
    lhs.cabin_state_Z == rhs.cabin_state_Z &&
    lhs.cabin_state_speed == rhs.cabin_state_speed &&
    lhs.motion_status == rhs.motion_status &&
    lhs.internal_calc_error == rhs.internal_calc_error &&
    lhs.device_alarm == rhs.device_alarm &&
    lhs.cabin_connect_flag == rhs.cabin_connect_flag;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::chassis_ctrl::cabin_upload_<ContainerAllocator1> & lhs, const ::chassis_ctrl::cabin_upload_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace chassis_ctrl

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::chassis_ctrl::cabin_upload_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chassis_ctrl::cabin_upload_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chassis_ctrl::cabin_upload_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chassis_ctrl::cabin_upload_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chassis_ctrl::cabin_upload_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chassis_ctrl::cabin_upload_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chassis_ctrl::cabin_upload_<ContainerAllocator> >
{
  static const char* value()
  {
    return "98ec7eb27dab261bc2b6c2dac6d6360e";
  }

  static const char* value(const ::chassis_ctrl::cabin_upload_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x98ec7eb27dab261bULL;
  static const uint64_t static_value2 = 0xc2b6c2dac6d6360eULL;
};

template<class ContainerAllocator>
struct DataType< ::chassis_ctrl::cabin_upload_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chassis_ctrl/cabin_upload";
  }

  static const char* value(const ::chassis_ctrl::cabin_upload_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chassis_ctrl::cabin_upload_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 这个msg是实现索驱模组模块上传数据。\n"
"#索驱部分数据反馈\n"
"float64 cabin_state_X \n"
"float64 cabin_state_Y \n"
"float64 cabin_state_Z \n"
"float64 cabin_state_speed \n"
"int32 motion_status\n"
"int32 internal_calc_error\n"
"int32 device_alarm\n"
"int32 cabin_connect_flag #这个标志位判断机器人是否连上索驱上位机\n"
"\n"
"# 机器人属性1\n"
"#float64 robot_pitch\n"
"#float64 robot_roll\n"
"#float64 robot_yaw\n"
;
  }

  static const char* value(const ::chassis_ctrl::cabin_upload_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chassis_ctrl::cabin_upload_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cabin_state_X);
      stream.next(m.cabin_state_Y);
      stream.next(m.cabin_state_Z);
      stream.next(m.cabin_state_speed);
      stream.next(m.motion_status);
      stream.next(m.internal_calc_error);
      stream.next(m.device_alarm);
      stream.next(m.cabin_connect_flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cabin_upload_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chassis_ctrl::cabin_upload_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::chassis_ctrl::cabin_upload_<ContainerAllocator>& v)
  {
    s << indent << "cabin_state_X: ";
    Printer<double>::stream(s, indent + "  ", v.cabin_state_X);
    s << indent << "cabin_state_Y: ";
    Printer<double>::stream(s, indent + "  ", v.cabin_state_Y);
    s << indent << "cabin_state_Z: ";
    Printer<double>::stream(s, indent + "  ", v.cabin_state_Z);
    s << indent << "cabin_state_speed: ";
    Printer<double>::stream(s, indent + "  ", v.cabin_state_speed);
    s << indent << "motion_status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.motion_status);
    s << indent << "internal_calc_error: ";
    Printer<int32_t>::stream(s, indent + "  ", v.internal_calc_error);
    s << indent << "device_alarm: ";
    Printer<int32_t>::stream(s, indent + "  ", v.device_alarm);
    s << indent << "cabin_connect_flag: ";
    Printer<int32_t>::stream(s, indent + "  ", v.cabin_connect_flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CHASSIS_CTRL_MESSAGE_CABIN_UPLOAD_H
