// Generated by gencpp from file chassis_ctrl/linear_module_upload.msg
// DO NOT EDIT!


#ifndef CHASSIS_CTRL_MESSAGE_LINEAR_MODULE_UPLOAD_H
#define CHASSIS_CTRL_MESSAGE_LINEAR_MODULE_UPLOAD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace chassis_ctrl
{
template <class ContainerAllocator>
struct linear_module_upload_
{
  typedef linear_module_upload_<ContainerAllocator> Type;

  linear_module_upload_()
    : linear_module_position_X(0.0)
    , linear_module_position_Y(0.0)
    , linear_module_position_Z(0.0)
    , linear_module_speed_X(0.0)
    , linear_module_speed_Y(0.0)
    , linear_module_speed_Z(0.0)
    , linear_module_error_flag_X(0)
    , linear_module_error_flag_Y(0)
    , linear_module_error_flag_Z(0)
    , motor_angle(0.0)
    , motor_speed(0.0)
    , motor_error_flag(0)
    , robot_battery_voltage(0.0)
    , robot_temperature(0.0)
    , x_gesture(0.0)
    , y_gesture(0.0)  {
    }
  linear_module_upload_(const ContainerAllocator& _alloc)
    : linear_module_position_X(0.0)
    , linear_module_position_Y(0.0)
    , linear_module_position_Z(0.0)
    , linear_module_speed_X(0.0)
    , linear_module_speed_Y(0.0)
    , linear_module_speed_Z(0.0)
    , linear_module_error_flag_X(0)
    , linear_module_error_flag_Y(0)
    , linear_module_error_flag_Z(0)
    , motor_angle(0.0)
    , motor_speed(0.0)
    , motor_error_flag(0)
    , robot_battery_voltage(0.0)
    , robot_temperature(0.0)
    , x_gesture(0.0)
    , y_gesture(0.0)  {
  (void)_alloc;
    }



   typedef double _linear_module_position_X_type;
  _linear_module_position_X_type linear_module_position_X;

   typedef double _linear_module_position_Y_type;
  _linear_module_position_Y_type linear_module_position_Y;

   typedef double _linear_module_position_Z_type;
  _linear_module_position_Z_type linear_module_position_Z;

   typedef double _linear_module_speed_X_type;
  _linear_module_speed_X_type linear_module_speed_X;

   typedef double _linear_module_speed_Y_type;
  _linear_module_speed_Y_type linear_module_speed_Y;

   typedef double _linear_module_speed_Z_type;
  _linear_module_speed_Z_type linear_module_speed_Z;

   typedef int32_t _linear_module_error_flag_X_type;
  _linear_module_error_flag_X_type linear_module_error_flag_X;

   typedef int32_t _linear_module_error_flag_Y_type;
  _linear_module_error_flag_Y_type linear_module_error_flag_Y;

   typedef int32_t _linear_module_error_flag_Z_type;
  _linear_module_error_flag_Z_type linear_module_error_flag_Z;

   typedef double _motor_angle_type;
  _motor_angle_type motor_angle;

   typedef double _motor_speed_type;
  _motor_speed_type motor_speed;

   typedef int32_t _motor_error_flag_type;
  _motor_error_flag_type motor_error_flag;

   typedef double _robot_battery_voltage_type;
  _robot_battery_voltage_type robot_battery_voltage;

   typedef double _robot_temperature_type;
  _robot_temperature_type robot_temperature;

   typedef float _x_gesture_type;
  _x_gesture_type x_gesture;

   typedef float _y_gesture_type;
  _y_gesture_type y_gesture;





  typedef boost::shared_ptr< ::chassis_ctrl::linear_module_upload_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chassis_ctrl::linear_module_upload_<ContainerAllocator> const> ConstPtr;

}; // struct linear_module_upload_

typedef ::chassis_ctrl::linear_module_upload_<std::allocator<void> > linear_module_upload;

typedef boost::shared_ptr< ::chassis_ctrl::linear_module_upload > linear_module_uploadPtr;
typedef boost::shared_ptr< ::chassis_ctrl::linear_module_upload const> linear_module_uploadConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chassis_ctrl::linear_module_upload_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chassis_ctrl::linear_module_upload_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::chassis_ctrl::linear_module_upload_<ContainerAllocator1> & lhs, const ::chassis_ctrl::linear_module_upload_<ContainerAllocator2> & rhs)
{
  return lhs.linear_module_position_X == rhs.linear_module_position_X &&
    lhs.linear_module_position_Y == rhs.linear_module_position_Y &&
    lhs.linear_module_position_Z == rhs.linear_module_position_Z &&
    lhs.linear_module_speed_X == rhs.linear_module_speed_X &&
    lhs.linear_module_speed_Y == rhs.linear_module_speed_Y &&
    lhs.linear_module_speed_Z == rhs.linear_module_speed_Z &&
    lhs.linear_module_error_flag_X == rhs.linear_module_error_flag_X &&
    lhs.linear_module_error_flag_Y == rhs.linear_module_error_flag_Y &&
    lhs.linear_module_error_flag_Z == rhs.linear_module_error_flag_Z &&
    lhs.motor_angle == rhs.motor_angle &&
    lhs.motor_speed == rhs.motor_speed &&
    lhs.motor_error_flag == rhs.motor_error_flag &&
    lhs.robot_battery_voltage == rhs.robot_battery_voltage &&
    lhs.robot_temperature == rhs.robot_temperature &&
    lhs.x_gesture == rhs.x_gesture &&
    lhs.y_gesture == rhs.y_gesture;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::chassis_ctrl::linear_module_upload_<ContainerAllocator1> & lhs, const ::chassis_ctrl::linear_module_upload_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace chassis_ctrl

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::chassis_ctrl::linear_module_upload_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chassis_ctrl::linear_module_upload_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chassis_ctrl::linear_module_upload_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chassis_ctrl::linear_module_upload_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chassis_ctrl::linear_module_upload_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chassis_ctrl::linear_module_upload_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chassis_ctrl::linear_module_upload_<ContainerAllocator> >
{
  static const char* value()
  {
    return "81ce67c2e9be4b936e5f25a32a87a2d3";
  }

  static const char* value(const ::chassis_ctrl::linear_module_upload_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x81ce67c2e9be4b93ULL;
  static const uint64_t static_value2 = 0x6e5f25a32a87a2d3ULL;
};

template<class ContainerAllocator>
struct DataType< ::chassis_ctrl::linear_module_upload_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chassis_ctrl/linear_module_upload";
  }

  static const char* value(const ::chassis_ctrl::linear_module_upload_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chassis_ctrl::linear_module_upload_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#这个msg是实现线性模组模块上传数据。\n"
"\n"
"#线性模组\n"
"float64 linear_module_position_X\n"
"float64 linear_module_position_Y\n"
"float64 linear_module_position_Z\n"
"float64 linear_module_speed_X\n"
"float64 linear_module_speed_Y\n"
"float64 linear_module_speed_Z\n"
"int32 linear_module_error_flag_X\n"
"int32 linear_module_error_flag_Y\n"
"int32 linear_module_error_flag_Z\n"
"\n"
"#旋转电机\n"
"float64 motor_angle\n"
"float64 motor_speed\n"
"int32 motor_error_flag\n"
"\n"
"#机器人属性1\n"
"float64 robot_battery_voltage\n"
"float64 robot_temperature\n"
"\n"
"#机器人倾角\n"
"float32 x_gesture\n"
"float32 y_gesture\n"
"\n"
"\n"
"\n"
;
  }

  static const char* value(const ::chassis_ctrl::linear_module_upload_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chassis_ctrl::linear_module_upload_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.linear_module_position_X);
      stream.next(m.linear_module_position_Y);
      stream.next(m.linear_module_position_Z);
      stream.next(m.linear_module_speed_X);
      stream.next(m.linear_module_speed_Y);
      stream.next(m.linear_module_speed_Z);
      stream.next(m.linear_module_error_flag_X);
      stream.next(m.linear_module_error_flag_Y);
      stream.next(m.linear_module_error_flag_Z);
      stream.next(m.motor_angle);
      stream.next(m.motor_speed);
      stream.next(m.motor_error_flag);
      stream.next(m.robot_battery_voltage);
      stream.next(m.robot_temperature);
      stream.next(m.x_gesture);
      stream.next(m.y_gesture);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct linear_module_upload_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chassis_ctrl::linear_module_upload_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::chassis_ctrl::linear_module_upload_<ContainerAllocator>& v)
  {
    s << indent << "linear_module_position_X: ";
    Printer<double>::stream(s, indent + "  ", v.linear_module_position_X);
    s << indent << "linear_module_position_Y: ";
    Printer<double>::stream(s, indent + "  ", v.linear_module_position_Y);
    s << indent << "linear_module_position_Z: ";
    Printer<double>::stream(s, indent + "  ", v.linear_module_position_Z);
    s << indent << "linear_module_speed_X: ";
    Printer<double>::stream(s, indent + "  ", v.linear_module_speed_X);
    s << indent << "linear_module_speed_Y: ";
    Printer<double>::stream(s, indent + "  ", v.linear_module_speed_Y);
    s << indent << "linear_module_speed_Z: ";
    Printer<double>::stream(s, indent + "  ", v.linear_module_speed_Z);
    s << indent << "linear_module_error_flag_X: ";
    Printer<int32_t>::stream(s, indent + "  ", v.linear_module_error_flag_X);
    s << indent << "linear_module_error_flag_Y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.linear_module_error_flag_Y);
    s << indent << "linear_module_error_flag_Z: ";
    Printer<int32_t>::stream(s, indent + "  ", v.linear_module_error_flag_Z);
    s << indent << "motor_angle: ";
    Printer<double>::stream(s, indent + "  ", v.motor_angle);
    s << indent << "motor_speed: ";
    Printer<double>::stream(s, indent + "  ", v.motor_speed);
    s << indent << "motor_error_flag: ";
    Printer<int32_t>::stream(s, indent + "  ", v.motor_error_flag);
    s << indent << "robot_battery_voltage: ";
    Printer<double>::stream(s, indent + "  ", v.robot_battery_voltage);
    s << indent << "robot_temperature: ";
    Printer<double>::stream(s, indent + "  ", v.robot_temperature);
    s << indent << "x_gesture: ";
    Printer<float>::stream(s, indent + "  ", v.x_gesture);
    s << indent << "y_gesture: ";
    Printer<float>::stream(s, indent + "  ", v.y_gesture);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CHASSIS_CTRL_MESSAGE_LINEAR_MODULE_UPLOAD_H
