// Generated by gencpp from file chassis_ctrl/linear_module_single_move.msg
// DO NOT EDIT!


#ifndef CHASSIS_CTRL_MESSAGE_LINEAR_MODULE_SINGLE_MOVE_H
#define CHASSIS_CTRL_MESSAGE_LINEAR_MODULE_SINGLE_MOVE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace chassis_ctrl
{
template <class ContainerAllocator>
struct linear_module_single_move_
{
  typedef linear_module_single_move_<ContainerAllocator> Type;

  linear_module_single_move_()
    : Axis(0)
    , target_distance(0.0)  {
    }
  linear_module_single_move_(const ContainerAllocator& _alloc)
    : Axis(0)
    , target_distance(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _Axis_type;
  _Axis_type Axis;

   typedef double _target_distance_type;
  _target_distance_type target_distance;





  typedef boost::shared_ptr< ::chassis_ctrl::linear_module_single_move_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chassis_ctrl::linear_module_single_move_<ContainerAllocator> const> ConstPtr;

}; // struct linear_module_single_move_

typedef ::chassis_ctrl::linear_module_single_move_<std::allocator<void> > linear_module_single_move;

typedef boost::shared_ptr< ::chassis_ctrl::linear_module_single_move > linear_module_single_movePtr;
typedef boost::shared_ptr< ::chassis_ctrl::linear_module_single_move const> linear_module_single_moveConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chassis_ctrl::linear_module_single_move_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chassis_ctrl::linear_module_single_move_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::chassis_ctrl::linear_module_single_move_<ContainerAllocator1> & lhs, const ::chassis_ctrl::linear_module_single_move_<ContainerAllocator2> & rhs)
{
  return lhs.Axis == rhs.Axis &&
    lhs.target_distance == rhs.target_distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::chassis_ctrl::linear_module_single_move_<ContainerAllocator1> & lhs, const ::chassis_ctrl::linear_module_single_move_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace chassis_ctrl

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::chassis_ctrl::linear_module_single_move_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chassis_ctrl::linear_module_single_move_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chassis_ctrl::linear_module_single_move_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chassis_ctrl::linear_module_single_move_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chassis_ctrl::linear_module_single_move_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chassis_ctrl::linear_module_single_move_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chassis_ctrl::linear_module_single_move_<ContainerAllocator> >
{
  static const char* value()
  {
    return "95c78978b1e0335834ff4f377cb83a75";
  }

  static const char* value(const ::chassis_ctrl::linear_module_single_move_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x95c78978b1e03358ULL;
  static const uint64_t static_value2 = 0x34ff4f377cb83a75ULL;
};

template<class ContainerAllocator>
struct DataType< ::chassis_ctrl::linear_module_single_move_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chassis_ctrl/linear_module_single_move";
  }

  static const char* value(const ::chassis_ctrl::linear_module_single_move_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chassis_ctrl::linear_module_single_move_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 这个msg为了触发单轴运动的回调函数\n"
"int32 Axis #操纵的轴体\n"
"float64 target_distance #移动的距离\n"
;
  }

  static const char* value(const ::chassis_ctrl::linear_module_single_move_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chassis_ctrl::linear_module_single_move_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Axis);
      stream.next(m.target_distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct linear_module_single_move_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chassis_ctrl::linear_module_single_move_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::chassis_ctrl::linear_module_single_move_<ContainerAllocator>& v)
  {
    s << indent << "Axis: ";
    Printer<int32_t>::stream(s, indent + "  ", v.Axis);
    s << indent << "target_distance: ";
    Printer<double>::stream(s, indent + "  ", v.target_distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CHASSIS_CTRL_MESSAGE_LINEAR_MODULE_SINGLE_MOVE_H
