// Generated by gencpp from file chassis_ctrl/linear_module_move_all.msg
// DO NOT EDIT!


#ifndef CHASSIS_CTRL_MESSAGE_LINEAR_MODULE_MOVE_ALL_H
#define CHASSIS_CTRL_MESSAGE_LINEAR_MODULE_MOVE_ALL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace chassis_ctrl
{
template <class ContainerAllocator>
struct linear_module_move_all_
{
  typedef linear_module_move_all_<ContainerAllocator> Type;

  linear_module_move_all_()
    : linear_module_X_distance(0.0)
    , linear_module_Y_distance(0.0)
    , linear_module_Z_distance(0.0)  {
    }
  linear_module_move_all_(const ContainerAllocator& _alloc)
    : linear_module_X_distance(0.0)
    , linear_module_Y_distance(0.0)
    , linear_module_Z_distance(0.0)  {
  (void)_alloc;
    }



   typedef double _linear_module_X_distance_type;
  _linear_module_X_distance_type linear_module_X_distance;

   typedef double _linear_module_Y_distance_type;
  _linear_module_Y_distance_type linear_module_Y_distance;

   typedef double _linear_module_Z_distance_type;
  _linear_module_Z_distance_type linear_module_Z_distance;





  typedef boost::shared_ptr< ::chassis_ctrl::linear_module_move_all_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chassis_ctrl::linear_module_move_all_<ContainerAllocator> const> ConstPtr;

}; // struct linear_module_move_all_

typedef ::chassis_ctrl::linear_module_move_all_<std::allocator<void> > linear_module_move_all;

typedef boost::shared_ptr< ::chassis_ctrl::linear_module_move_all > linear_module_move_allPtr;
typedef boost::shared_ptr< ::chassis_ctrl::linear_module_move_all const> linear_module_move_allConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chassis_ctrl::linear_module_move_all_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chassis_ctrl::linear_module_move_all_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::chassis_ctrl::linear_module_move_all_<ContainerAllocator1> & lhs, const ::chassis_ctrl::linear_module_move_all_<ContainerAllocator2> & rhs)
{
  return lhs.linear_module_X_distance == rhs.linear_module_X_distance &&
    lhs.linear_module_Y_distance == rhs.linear_module_Y_distance &&
    lhs.linear_module_Z_distance == rhs.linear_module_Z_distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::chassis_ctrl::linear_module_move_all_<ContainerAllocator1> & lhs, const ::chassis_ctrl::linear_module_move_all_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace chassis_ctrl

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::chassis_ctrl::linear_module_move_all_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chassis_ctrl::linear_module_move_all_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chassis_ctrl::linear_module_move_all_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chassis_ctrl::linear_module_move_all_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chassis_ctrl::linear_module_move_all_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chassis_ctrl::linear_module_move_all_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chassis_ctrl::linear_module_move_all_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5b2b6e0e4fe8da65ffa4311ceb10cbbe";
  }

  static const char* value(const ::chassis_ctrl::linear_module_move_all_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5b2b6e0e4fe8da65ULL;
  static const uint64_t static_value2 = 0xffa4311ceb10cbbeULL;
};

template<class ContainerAllocator>
struct DataType< ::chassis_ctrl::linear_module_move_all_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chassis_ctrl/linear_module_move_all";
  }

  static const char* value(const ::chassis_ctrl::linear_module_move_all_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chassis_ctrl::linear_module_move_all_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 这个msg为了触发线性模组三轴运动的回调函数\n"
"float64 linear_module_X_distance\n"
"float64 linear_module_Y_distance\n"
"float64 linear_module_Z_distance\n"
;
  }

  static const char* value(const ::chassis_ctrl::linear_module_move_all_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chassis_ctrl::linear_module_move_all_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.linear_module_X_distance);
      stream.next(m.linear_module_Y_distance);
      stream.next(m.linear_module_Z_distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct linear_module_move_all_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chassis_ctrl::linear_module_move_all_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::chassis_ctrl::linear_module_move_all_<ContainerAllocator>& v)
  {
    s << indent << "linear_module_X_distance: ";
    Printer<double>::stream(s, indent + "  ", v.linear_module_X_distance);
    s << indent << "linear_module_Y_distance: ";
    Printer<double>::stream(s, indent + "  ", v.linear_module_Y_distance);
    s << indent << "linear_module_Z_distance: ";
    Printer<double>::stream(s, indent + "  ", v.linear_module_Z_distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CHASSIS_CTRL_MESSAGE_LINEAR_MODULE_MOVE_ALL_H
