// Generated by gencpp from file chassis_ctrl/motion.msg
// DO NOT EDIT!


#ifndef CHASSIS_CTRL_MESSAGE_MOTION_H
#define CHASSIS_CTRL_MESSAGE_MOTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace chassis_ctrl
{
template <class ContainerAllocator>
struct motion_
{
  typedef motion_<ContainerAllocator> Type;

  motion_()
    : data()
    , p_index(0)
    , p_count(0)  {
    }
  motion_(const ContainerAllocator& _alloc)
    : data(_alloc)
    , p_index(0)
    , p_count(0)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _data_type;
  _data_type data;

   typedef int32_t _p_index_type;
  _p_index_type p_index;

   typedef int32_t _p_count_type;
  _p_count_type p_count;





  typedef boost::shared_ptr< ::chassis_ctrl::motion_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chassis_ctrl::motion_<ContainerAllocator> const> ConstPtr;

}; // struct motion_

typedef ::chassis_ctrl::motion_<std::allocator<void> > motion;

typedef boost::shared_ptr< ::chassis_ctrl::motion > motionPtr;
typedef boost::shared_ptr< ::chassis_ctrl::motion const> motionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chassis_ctrl::motion_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chassis_ctrl::motion_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::chassis_ctrl::motion_<ContainerAllocator1> & lhs, const ::chassis_ctrl::motion_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data &&
    lhs.p_index == rhs.p_index &&
    lhs.p_count == rhs.p_count;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::chassis_ctrl::motion_<ContainerAllocator1> & lhs, const ::chassis_ctrl::motion_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace chassis_ctrl

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::chassis_ctrl::motion_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chassis_ctrl::motion_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chassis_ctrl::motion_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chassis_ctrl::motion_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chassis_ctrl::motion_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chassis_ctrl::motion_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chassis_ctrl::motion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2c6df0a90771d657ebbf1f518663d736";
  }

  static const char* value(const ::chassis_ctrl::motion_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2c6df0a90771d657ULL;
  static const uint64_t static_value2 = 0xebbf1f518663d736ULL;
};

template<class ContainerAllocator>
struct DataType< ::chassis_ctrl::motion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chassis_ctrl/motion";
  }

  static const char* value(const ::chassis_ctrl::motion_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chassis_ctrl::motion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# (x,y,z,theta_z;....;....;)， 坐标值/z轴目标角度 \n"
"float32[] data  # mm\n"
"\n"
"#区域内已经绑扎点的数量\n"
"int32 p_index\n"
"#区域内需要绑扎点的总数量\n"
"int32 p_count\n"
"\n"
"# # 定位每个目标时，三个方向的速度值, 根据电机给定\n"
"# float32 v_x\n"
"# float32 v_y\n"
"# float32 v_z\n"
"\n"
"# # xyz执行量\n"
"# float32 d_x\n"
"# float32 d_y\n"
"# float32 d_z\n"
"\n"
"# # xyz 执行时间, 用于响应截止\n"
"# float32 t_x # unit: s\n"
"# float32 t_y\n"
"# float32 t_z\n"
"\n"
"# # xyz动作执行方向\n"
"# int32 dir_x\n"
"# int32 dir_y\n"
"# int32 dir_z\n"
"\n"
"# # 判断xyz,b_cybergear动作执行完成\n"
"# bool b_x\n"
"# bool b_y\n"
"# bool b_z\n"
"# bool b_cybergear\n"
"\n"
"# # 判断钢筋绑扎完成\n"
"# bool action_f\n"
;
  }

  static const char* value(const ::chassis_ctrl::motion_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chassis_ctrl::motion_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
      stream.next(m.p_index);
      stream.next(m.p_count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motion_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chassis_ctrl::motion_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::chassis_ctrl::motion_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.data[i]);
    }
    s << indent << "p_index: ";
    Printer<int32_t>::stream(s, indent + "  ", v.p_index);
    s << indent << "p_count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.p_count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CHASSIS_CTRL_MESSAGE_MOTION_H
