home_cabin_mm:
  x: 161.2
  y: 917.1
  z: 510.2
base_to_camera_mm:
  x: 0.0
  y: 0.0
  z: 460.0
base_to_camera_rpy:
  roll: 3.141592653589793
  pitch: 0.0
  yaw: 0.0
cabin_to_map_sign:
  x: 1.0
  y: 1.0
  z: 1.0
