export const SYSTEM_CONTROL_ACTIONS = [
  {
    id: "startRosStack",
    label: "启动 ROS",
    description: "拉起整套运行栈与前端静态服务",
    serviceKey: null,
    httpEndpoint: "/api/system/start_ros_stack",
    tone: "green",
  },
  {
    id: "startDriverStack",
    label: "启动驱动层",
    description: "拉起索驱、末端和虎口 TF 运行栈",
    serviceKey: "startDriverStackService",
    httpEndpoint: "/api/system/start_driver_stack",
    tone: "green",
  },
  {
    id: "restartDriverStack",
    label: "重启驱动层",
    description: "重启索驱、末端和虎口 TF 运行栈",
    serviceKey: "restartDriverStackService",
    httpEndpoint: "/api/system/restart_driver_stack",
    tone: "amber",
  },
  {
    id: "startCabinDriver",
    label: "启动索驱",
    description: "启动索驱底层 TCP 驱动连接",
    serviceKey: "startCabinDriverService",
    httpEndpoint: null,
    tone: "green",
  },
  {
    id: "stopCabinDriver",
    label: "关闭索驱",
    description: "关闭索驱底层 TCP 驱动连接",
    serviceKey: "stopCabinDriverService",
    httpEndpoint: null,
    tone: "amber",
  },
  {
    id: "restartCabinDriver",
    label: "重启索驱",
    description: "重启索驱底层 TCP 驱动连接",
    serviceKey: "restartCabinDriverService",
    httpEndpoint: null,
    tone: "amber",
  },
  {
    id: "startModuanDriver",
    label: "启动末端",
    description: "启动末端 Modbus 驱动连接",
    serviceKey: "startModuanDriverService",
    httpEndpoint: null,
    tone: "green",
  },
  {
    id: "stopModuanDriver",
    label: "关闭末端",
    description: "关闭末端 Modbus 驱动连接",
    serviceKey: "stopModuanDriverService",
    httpEndpoint: null,
    tone: "amber",
  },
  {
    id: "restartModuanDriver",
    label: "重启末端",
    description: "重启末端 Modbus 驱动连接",
    serviceKey: "restartModuanDriverService",
    httpEndpoint: null,
    tone: "amber",
  },
  {
    id: "startAlgorithmStack",
    label: "启动算法层",
    description: "拉起 pointAI 与稳定点 TF 算法链",
    serviceKey: "startAlgorithmStackService",
    httpEndpoint: "/api/system/start_algorithm_stack",
    tone: "blue",
  },
  {
    id: "restartAlgorithmStack",
    label: "重启算法层",
    description: "重启 pointAI 与稳定点 TF 算法链",
    serviceKey: "restartAlgorithmStackService",
    httpEndpoint: "/api/system/restart_algorithm_stack",
    tone: "amber",
  },
  {
    id: "restartRosStack",
    label: "重启 ROS",
    description: "重启运行栈，不重启前端静态服务",
    serviceKey: "restartRosStackService",
    httpEndpoint: "/api/system/restart_ros_stack",
    tone: "amber",
  },
];

export function getSystemControlAction(actionId) {
  return SYSTEM_CONTROL_ACTIONS.find((item) => item.id === actionId) || null;
}
