export const SYSTEM_CONTROL_ACTIONS = [
  {
    id: "toggleDemoMode",
    label: "演示模式",
    description: "切换 5173 旧前端与 chassis_ctrl show_full.launch 演示模式",
    serviceKey: null,
    httpEndpoint: "/api/system/toggle_demo_mode",
    statusEndpoint: "/api/system/demo_mode_status",
    tone: "red",
  },
  {
    id: "startRosStack",
    label: "启动 ROS",
    description: "通过 systemd 拉起 ROS 后端运行栈",
    serviceKey: null,
    httpEndpoint: "/api/system/start_ros_stack",
    tone: "green",
  },
  {
    id: "stopRosStack",
    label: "停止 ROS",
    description: "通过 systemd 停止 ROS 后端运行栈",
    serviceKey: null,
    httpEndpoint: "/api/system/stop_ros_stack",
    tone: "amber",
  },
  {
    id: "startDriverStack",
    label: "启动驱动层",
    description: "通过 systemd 拉起索驱、线性模组和相机驱动守护",
    serviceKey: null,
    httpEndpoint: "/api/system/start_driver_stack",
    tone: "green",
  },
  {
    id: "stopDriverStack",
    label: "停止驱动层",
    description: "通过 systemd 停止索驱、线性模组和相机驱动守护",
    serviceKey: null,
    httpEndpoint: "/api/system/stop_driver_stack",
    tone: "amber",
  },
  {
    id: "restartDriverStack",
    label: "重启驱动层",
    description: "通过 systemd 重启索驱、线性模组和相机驱动守护",
    serviceKey: null,
    httpEndpoint: "/api/system/restart_driver_stack",
    tone: "amber",
  },
  {
    id: "startCabinDriver",
    label: "启动索驱",
    description: "通过 systemd 启动索驱 TCP 驱动守护",
    serviceKey: null,
    httpEndpoint: "/api/system/start_cabin_driver",
    tone: "green",
  },
  {
    id: "stopCabinDriver",
    label: "关闭索驱",
    description: "通过 systemd 停止索驱 TCP 驱动守护",
    serviceKey: null,
    httpEndpoint: "/api/system/stop_cabin_driver",
    tone: "amber",
  },
  {
    id: "restartCabinDriver",
    label: "重启索驱",
    description: "通过 systemd 重启索驱 TCP 驱动守护",
    serviceKey: null,
    httpEndpoint: "/api/system/restart_cabin_driver",
    tone: "amber",
  },
  {
    id: "startModuanDriver",
    label: "启动线模",
    description: "通过 systemd 启动线性模组 Modbus 驱动守护",
    serviceKey: null,
    httpEndpoint: "/api/system/start_moduan_driver",
    tone: "green",
  },
  {
    id: "stopModuanDriver",
    label: "关闭线模",
    description: "通过 systemd 停止线性模组 Modbus 驱动守护",
    serviceKey: null,
    httpEndpoint: "/api/system/stop_moduan_driver",
    tone: "amber",
  },
  {
    id: "restartModuanDriver",
    label: "重启线模",
    description: "通过 systemd 重启线性模组 Modbus 驱动守护",
    serviceKey: null,
    httpEndpoint: "/api/system/restart_moduan_driver",
    tone: "amber",
  },
  {
    id: "startCameraDriver",
    label: "启动相机",
    description: "通过 systemd 启动相机驱动守护",
    serviceKey: null,
    httpEndpoint: "/api/system/start_camera_driver",
    tone: "green",
  },
  {
    id: "stopCameraDriver",
    label: "关闭相机",
    description: "通过 systemd 停止相机驱动守护",
    serviceKey: null,
    httpEndpoint: "/api/system/stop_camera_driver",
    tone: "amber",
  },
  {
    id: "restartCameraDriver",
    label: "重启相机",
    description: "通过 systemd 重启相机驱动守护",
    serviceKey: null,
    httpEndpoint: "/api/system/restart_camera_driver",
    tone: "amber",
  },
  {
    id: "startAlgorithmStack",
    label: "启动算法层",
    description: "拉起 pointAI 与稳定点 TF 算法链",
    serviceKey: null,
    httpEndpoint: "/api/system/start_algorithm_stack",
    tone: "blue",
  },
  {
    id: "stopAlgorithmStack",
    label: "停止算法层",
    description: "停止 pointAI、构图、规划与执行编排算法链",
    serviceKey: null,
    httpEndpoint: "/api/system/stop_algorithm_stack",
    tone: "amber",
  },
  {
    id: "restartAlgorithmStack",
    label: "重启算法层",
    description: "重启 pointAI 与稳定点 TF 算法链",
    serviceKey: null,
    httpEndpoint: "/api/system/restart_algorithm_stack",
    tone: "amber",
  },
  {
    id: "startCabinSubsystem",
    label: "启动索驱子系统",
    description: "只启动索驱驱动层，不影响末端或视觉层",
    serviceKey: null,
    steps: ["startCabinDriver"],
    tone: "green",
  },
  {
    id: "restartCabinSubsystem",
    label: "重启索驱子系统",
    description: "只重启索驱驱动层，不影响末端或视觉层",
    serviceKey: null,
    steps: ["restartCabinDriver"],
    tone: "amber",
  },
  {
    id: "stopCabinSubsystem",
    label: "关闭索驱子系统",
    description: "只停止索驱驱动层，不影响末端或视觉层",
    serviceKey: null,
    steps: ["stopCabinDriver"],
    tone: "amber",
  },
  {
    id: "startModuanSubsystem",
    label: "启动末端子系统",
    description: "只启动线性模组驱动层，不影响索驱或视觉层",
    serviceKey: null,
    steps: ["startModuanDriver"],
    tone: "green",
  },
  {
    id: "stopModuanSubsystem",
    label: "关闭末端子系统",
    description: "只停止线性模组驱动层，不影响索驱或视觉层",
    serviceKey: null,
    steps: ["stopModuanDriver"],
    tone: "amber",
  },
  {
    id: "restartModuanSubsystem",
    label: "重启末端子系统",
    description: "只重启线性模组驱动层，不影响索驱或视觉层",
    serviceKey: null,
    steps: ["restartModuanDriver"],
    tone: "amber",
  },
  {
    id: "startVisualSubsystem",
    label: "启动视觉子系统",
    description: "启动相机驱动层，并确保算法层在线",
    serviceKey: null,
    steps: ["startCameraDriver", "startAlgorithmStack"],
    tone: "green",
  },
  {
    id: "stopVisualSubsystem",
    label: "关闭视觉子系统",
    description: "先停止算法层，再停止相机驱动层",
    serviceKey: null,
    steps: ["stopAlgorithmStack", "stopCameraDriver"],
    tone: "amber",
  },
  {
    id: "restartVisualSubsystem",
    label: "重启视觉子系统",
    description: "重启相机驱动层，并确保算法层在线",
    serviceKey: null,
    steps: ["restartCameraDriver", "restartAlgorithmStack"],
    tone: "amber",
  },
  {
    id: "restartRosStack",
    label: "重启 ROS",
    description: "快速停止 rosbridge、驱动层和 ROS 后端，再按依赖顺序重新启动",
    serviceKey: null,
    httpEndpoint: "/api/system/restart_ros_stack",
    tone: "amber",
  },
];

export function getSystemControlAction(actionId) {
  return SYSTEM_CONTROL_ACTIONS.find((item) => item.id === actionId) || null;
}
