export const MESSAGE_TYPES = Object.freeze({
  diagnosticArray: "diagnostic_msgs/DiagnosticArray",
  float32: "std_msgs/Float32",
  float32MultiArray: "std_msgs/Float32MultiArray",
  int32: "std_msgs/Int32",
  image: "sensor_msgs/Image",
  cameraInfo: "sensor_msgs/CameraInfo",
  cabinState: "tie_robot_msgs/cabin_upload",
  linearModuleState: "tie_robot_msgs/linear_module_upload",
  log: "rosgraph_msgs/Log",
  markerArray: "visualization_msgs/MarkerArray",
  pointsArray: "tie_robot_msgs/PointsArray",
  pose: "geometry_msgs/Pose",
  tfMessage: "tf2_msgs/TFMessage",
  bool: "std_msgs/Bool",
});

export const SERVICE_TYPES = Object.freeze({
  cabin: Object.freeze({
    singleMove: "tie_robot_msgs/SingleMove",
    setExecutionMode: "tie_robot_msgs/SetExecutionMode",
  }),
  algorithm: Object.freeze({
    processImage: "tie_robot_msgs/ProcessImage",
  }),
  moduan: Object.freeze({
    linearModuleMove: "tie_robot_msgs/linear_module_move",
  }),
  tf: Object.freeze({
    setGripperTfCalibration: "tie_robot_msgs/SetGripperTfCalibration",
    robotHomeCalibration: "tie_robot_msgs/RobotHomeCalibration",
  }),
  trigger: "std_srvs/Trigger",
});

export const ACTION_TYPES = Object.freeze({
  cabin: Object.freeze({
    startPseudoSlamScan: "tie_robot_msgs/StartPseudoSlamScanTaskAction",
    startGlobalWork: "tie_robot_msgs/StartGlobalWorkTaskAction",
    runBindPathDirectTest: "tie_robot_msgs/RunBindPathDirectTestTaskAction",
  }),
});

export const TOPICS = Object.freeze({
  camera: Object.freeze({
    irImage: "/Scepter/ir/image_raw",
    irCameraInfo: "/Scepter/ir/camera_info",
    colorImage: "/Scepter/color/image_raw",
    depthImage: "/Scepter/depth/image_raw",
    filteredWorldCoord: "/Scepter/worldCoord/world_coord",
    rawWorldCoord: "/Scepter/worldCoord/raw_world_coord",
  }),
  algorithm: Object.freeze({
    coordinatePoint: "/perception/lashing/points_camera",
    currentWorkspaceQuadPixels: "/perception/lashing/workspace/quad_pixels",
    manualWorkspaceS2Points: "/perception/lashing/points_camera",
    manualWorkspaceS2ResultRaw: "/perception/lashing/result_image",
    scanSurfaceDpBaseImage: "/perception/lashing/scan_surface_dp_base_image",
    scanSurfaceDpCompletedSurfaceImage: "/perception/lashing/scan_surface_dp_completed_surface_image",
    executionRefineBaseImage: "/perception/lashing/execution_refine_base_image",
    resultImageRaw: "/pointAI/result_image_raw",
    setStableFrameCount: "/web/pointAI/set_stable_frame_count",
    setHeightThreshold: "/web/pointAI/set_height_threshold",
    setWorkspaceQuad: "/web/pointAI/set_workspace_quad",
  }),
  process: Object.freeze({
    areaProgress: "/cabin/area_progress",
    cabinState: "/cabin/cabin_data_upload",
    diagnostics: "/diagnostics",
    pseudoSlamMarkers: "/cabin/pseudo_slam_markers",
    setCabinSpeed: "/web/cabin/set_cabin_speed",
  }),
  control: Object.freeze({
    enableLashing: "/web/moduan/enb_las",
    forcedStop: "/web/moduan/forced_stop",
    handSolveWarn: "/web/moduan/hand_sovle_warn",
    interruptStop: "/web/moduan/interrupt_stop",
    light: "/web/moduan/light",
    linearModuleState: "/moduan/moduan_gesture_data",
    moduanMoveZero: "/web/moduan/moduan_move_zero",
    saveBindingData: "/web/moduan/save_binding_data",
    sendOddPoints: "/web/moduan/send_odd_points",
    setModuanSpeed: "/web/moduan/set_moduan_speed",
  }),
  tf: Object.freeze({
    live: "/tf",
    static: "/tf_static",
    setCameraTcpExtrinsic: "/web/tf/set_camera_tcp_extrinsic",
  }),
  logs: Object.freeze({
    all: "/system_log/all",
    cabin: "/system_log/suoqu_driver_node",
    camera: "/system_log/scepter_manager",
    moduan: "/system_log/moduan_driver_node",
  }),
});

export const SERVICES = Object.freeze({
  algorithm: Object.freeze({
    processImage: "/pointAI/process_image",
    recognizeOnce: "/perception/lashing/recognize_once",
  }),
  cabin: Object.freeze({
    driverRestart: "/cabin/driver/restart",
    driverStart: "/cabin/driver/start",
    driverStop: "/cabin/driver/stop",
    motionStop: "/cabin/motion/stop",
    setExecutionMode: "/cabin/set_execution_mode",
    singleMove: "/cabin/driver/raw_move",
    incrementalMove: "/cabin/driver/incremental_move",
  }),
  moduan: Object.freeze({
    driverRestart: "/moduan/driver/restart",
    driverStart: "/moduan/driver/start",
    driverStop: "/moduan/driver/stop",
    singleBind: "/moduan/sg",
    singleMove: "/moduan/single_move",
  }),
  system: Object.freeze({
    restartAlgorithmStack: "/web/system/restart_algorithm_stack",
    restartDriverStack: "/web/system/restart_driver_stack",
    restartRosStack: "/web/system/restart_ros_stack",
    startAlgorithmStack: "/web/system/start_algorithm_stack",
    startDriverStack: "/web/system/start_driver_stack",
  }),
  tf: Object.freeze({
    setGripperTfCalibration: "/web/tf/set_gripper_tf_calibration",
    robotHomeCalibration: "/web/tf/robot_home_calibration",
  }),
});

export const ACTIONS = Object.freeze({
  cabin: Object.freeze({
    runBindPathDirectTest: "/web/cabin/run_bind_path_direct_test",
    startGlobalWork: "/web/cabin/start_global_work",
    startPseudoSlamScan: "/web/cabin/start_pseudo_slam_scan",
  }),
});

export const FRONTEND_DIRECT_TOPIC_REGISTRY = Object.freeze([
  {
    key: "camera.irImage",
    name: TOPICS.camera.irImage,
    label: "红外原图",
    messageType: MESSAGE_TYPES.image,
    sourceLayer: "driver",
    sourceLabel: "相机驱动",
    ownerNode: "scepter_manager",
    direction: "subscribe",
    usage: "图像预览与工作区选点底图",
  },
  {
    key: "camera.irCameraInfo",
    name: TOPICS.camera.irCameraInfo,
    label: "红外相机内参",
    messageType: MESSAGE_TYPES.cameraInfo,
    sourceLayer: "driver",
    sourceLabel: "相机驱动",
    ownerNode: "scepter_manager",
    direction: "subscribe",
    usage: "红外图像 TCP 工作范围投影",
  },
  {
    key: "camera.colorImage",
    name: TOPICS.camera.colorImage,
    label: "彩色原图",
    messageType: MESSAGE_TYPES.image,
    sourceLayer: "driver",
    sourceLabel: "相机驱动",
    ownerNode: "scepter_manager",
    direction: "subscribe",
    usage: "相机彩色预览",
  },
  {
    key: "camera.depthImage",
    name: TOPICS.camera.depthImage,
    label: "深度原图",
    messageType: MESSAGE_TYPES.image,
    sourceLayer: "driver",
    sourceLabel: "相机驱动",
    ownerNode: "scepter_manager",
    direction: "subscribe",
    usage: "相机深度预览",
  },
  {
    key: "camera.filteredWorldCoord",
    name: TOPICS.camera.filteredWorldCoord,
    label: "滤波世界点云图",
    messageType: MESSAGE_TYPES.image,
    sourceLayer: "driver",
    sourceLabel: "相机驱动",
    ownerNode: "scepter_world_coord_processor",
    direction: "subscribe",
    usage: "三维点云图层",
  },
  {
    key: "camera.rawWorldCoord",
    name: TOPICS.camera.rawWorldCoord,
    label: "原始世界点云图",
    messageType: MESSAGE_TYPES.image,
    sourceLayer: "driver",
    sourceLabel: "相机驱动",
    ownerNode: "scepter_world_coord_processor",
    direction: "subscribe",
    usage: "三维点云图层原始数据",
  },
  {
    key: "algorithm.resultImageRaw",
    name: TOPICS.algorithm.resultImageRaw,
    label: "执行结果覆盖源图",
    messageType: MESSAGE_TYPES.image,
    sourceLayer: "algorithm",
    sourceLabel: "算法层",
    ownerNode: "pointAINode",
    direction: "subscribe",
    usage: "执行/视觉结果原始输出，前端不作为图像卡片独立图层",
  },
  {
    key: "algorithm.scanSurfaceDpBaseImage",
    name: TOPICS.algorithm.scanSurfaceDpBaseImage,
    label: "扫描底图 fused response",
    messageType: MESSAGE_TYPES.image,
    sourceLayer: "algorithm",
    sourceLabel: "扫描视觉层",
    ownerNode: "pointAINode",
    direction: "subscribe",
    usage: "Surface-DP 候选生成使用的融合响应底图",
  },
  {
    key: "algorithm.scanSurfaceDpCompletedSurfaceImage",
    name: TOPICS.algorithm.scanSurfaceDpCompletedSurfaceImage,
    label: "扫描DP收束底图",
    messageType: MESSAGE_TYPES.image,
    sourceLayer: "algorithm",
    sourceLabel: "扫描视觉层",
    ownerNode: "pointAINode",
    direction: "subscribe",
    usage: "Surface-DP 曲线收束使用的补全面响应底图",
  },
  {
    key: "algorithm.executionRefineBaseImage",
    name: TOPICS.algorithm.executionRefineBaseImage,
    label: "执行底图 Hough二值",
    messageType: MESSAGE_TYPES.image,
    sourceLayer: "algorithm",
    sourceLabel: "执行视觉层",
    ownerNode: "pointAINode",
    direction: "subscribe",
    usage: "执行微调平面分割 + Hough 使用的二值底图",
  },
  {
    key: "algorithm.manualWorkspaceS2ResultRaw",
    name: TOPICS.algorithm.manualWorkspaceS2ResultRaw,
    label: "视觉识别覆盖源图",
    messageType: MESSAGE_TYPES.image,
    sourceLayer: "algorithm",
    sourceLabel: "算法层",
    ownerNode: "pointAINode",
    direction: "subscribe",
    usage: "手动工作区识别结果覆盖层",
  },
  {
    key: "algorithm.manualWorkspaceS2Points",
    name: TOPICS.algorithm.manualWorkspaceS2Points,
    label: "视觉识别点位",
    messageType: MESSAGE_TYPES.pointsArray,
    sourceLayer: "algorithm",
    sourceLabel: "算法层",
    ownerNode: "pointAINode",
    direction: "subscribe",
    usage: "手动工作区视觉识别点位覆盖层",
  },
  {
    key: "algorithm.currentWorkspaceQuadPixels",
    name: TOPICS.algorithm.currentWorkspaceQuadPixels,
    label: "当前工作区像素四边形",
    messageType: MESSAGE_TYPES.float32MultiArray,
    sourceLayer: "algorithm",
    sourceLabel: "算法层",
    ownerNode: "pointAINode",
    direction: "subscribe",
    usage: "同步算法层保存的工作区",
  },
  {
    key: "algorithm.coordinatePoint",
    name: TOPICS.algorithm.coordinatePoint,
    label: "绑扎点数组",
    messageType: MESSAGE_TYPES.pointsArray,
    sourceLayer: "algorithm",
    sourceLabel: "算法层",
    ownerNode: "pointAINode",
    direction: "subscribe",
    usage: "相机坐标系原始绑扎点，前端显示时只通过 TF 变到 map",
  },
  {
    key: "algorithm.setWorkspaceQuad",
    name: TOPICS.algorithm.setWorkspaceQuad,
    label: "提交工作区四边形",
    messageType: MESSAGE_TYPES.float32MultiArray,
    sourceLayer: "algorithm",
    sourceLabel: "算法层",
    ownerNode: "pointAINode",
    direction: "publish",
    usage: "前端直接写入算法层工作区",
  },
  {
    key: "algorithm.setStableFrameCount",
    name: TOPICS.algorithm.setStableFrameCount,
    label: "设置视觉放行帧数",
    messageType: MESSAGE_TYPES.int32,
    sourceLayer: "algorithm",
    sourceLabel: "算法层",
    ownerNode: "pointAINode",
    direction: "publish",
    usage: "视觉调试页热更新 process_image 最终放行帧数",
  },
  {
    key: "algorithm.setHeightThreshold",
    name: TOPICS.algorithm.setHeightThreshold,
    label: "设置固定高度阈值",
    messageType: MESSAGE_TYPES.float32,
    sourceLayer: "algorithm",
    sourceLabel: "算法层",
    ownerNode: "pointAINode",
    direction: "publish",
    usage: "视觉调试参数",
  },
  {
    key: "process.pseudoSlamMarkers",
    name: TOPICS.process.pseudoSlamMarkers,
    label: "区域规划 Marker",
    messageType: MESSAGE_TYPES.markerArray,
    sourceLayer: "process",
    sourceLabel: "执行规划层",
    ownerNode: "suoquNode",
    direction: "subscribe",
    usage: "区域规划与账本路径显示",
  },
  {
    key: "process.cabinState",
    name: TOPICS.process.cabinState,
    label: "索驱实时状态",
    messageType: MESSAGE_TYPES.cabinState,
    sourceLayer: "process",
    sourceLabel: "执行规划层",
    ownerNode: "suoquNode",
    direction: "subscribe",
    usage: "索驱位置条和遥控可操作状态",
  },
  {
    key: "process.diagnostics",
    name: TOPICS.process.diagnostics,
    label: "诊断状态",
    messageType: MESSAGE_TYPES.diagnosticArray,
    sourceLayer: "process",
    sourceLabel: "运行诊断",
    ownerNode: "diagnostic_updater",
    direction: "subscribe",
    usage: "状态胶囊与问题提示",
  },
  {
    key: "process.setCabinSpeed",
    name: TOPICS.process.setCabinSpeed,
    label: "设置索驱全局速度",
    messageType: MESSAGE_TYPES.float32,
    sourceLayer: "process",
    sourceLabel: "执行规划层",
    ownerNode: "suoquNode",
    direction: "publish",
    usage: "前端直接写入索驱速度参数",
  },
  {
    key: "control.linearModuleState",
    name: TOPICS.control.linearModuleState,
    label: "线性模组状态",
    messageType: MESSAGE_TYPES.linearModuleState,
    sourceLayer: "control",
    sourceLabel: "控制层",
    ownerNode: "moduanNode",
    direction: "subscribe",
    usage: "TCP 线性模组位置与电压显示",
  },
  {
    key: "control.interruptStop",
    name: TOPICS.control.interruptStop,
    label: "暂停作业",
    messageType: MESSAGE_TYPES.float32,
    sourceLayer: "control",
    sourceLabel: "控制层",
    ownerNode: "moduanNode",
    direction: "publish",
    usage: "前端直接写入末端暂停控制",
  },
  {
    key: "control.enableLashing",
    name: TOPICS.control.enableLashing,
    label: "绑扎使能",
    messageType: MESSAGE_TYPES.float32,
    sourceLayer: "control",
    sourceLabel: "控制层",
    ownerNode: "moduanNode",
    direction: "publish",
    usage: "前端直接写入末端绑扎控制",
  },
  {
    key: "control.sendOddPoints",
    name: TOPICS.control.sendOddPoints,
    label: "跳绑开关",
    messageType: MESSAGE_TYPES.bool,
    sourceLayer: "control",
    sourceLabel: "控制层",
    ownerNode: "moduanNode",
    direction: "publish",
    usage: "前端直接写入跳绑控制，算法层同时读取该状态",
  },
  {
    key: "control.handSolveWarn",
    name: TOPICS.control.handSolveWarn,
    label: "恢复作业",
    messageType: MESSAGE_TYPES.float32,
    sourceLayer: "control",
    sourceLabel: "控制层",
    ownerNode: "moduanNode",
    direction: "publish",
    usage: "前端直接写入末端恢复控制",
  },
  {
    key: "control.light",
    name: TOPICS.control.light,
    label: "灯光开关",
    messageType: MESSAGE_TYPES.bool,
    sourceLayer: "control",
    sourceLabel: "控制层",
    ownerNode: "moduanNode",
    direction: "publish",
    usage: "前端直接写入末端灯光控制",
  },
  {
    key: "control.moduanMoveZero",
    name: TOPICS.control.moduanMoveZero,
    label: "末端回零",
    messageType: MESSAGE_TYPES.float32,
    sourceLayer: "control",
    sourceLabel: "控制层",
    ownerNode: "moduanNode",
    direction: "publish",
    usage: "前端直接触发线性模组回零",
  },
  {
    key: "control.forcedStop",
    name: TOPICS.control.forcedStop,
    label: "急停作业",
    messageType: MESSAGE_TYPES.float32,
    sourceLayer: "control",
    sourceLabel: "控制层",
    ownerNode: "moduanNode",
    direction: "publish",
    usage: "前端直接写入控制层急停",
  },
  {
    key: "control.setModuanSpeed",
    name: TOPICS.control.setModuanSpeed,
    label: "设置末端速度",
    messageType: MESSAGE_TYPES.float32,
    sourceLayer: "control",
    sourceLabel: "控制层",
    ownerNode: "moduanNode",
    direction: "publish",
    usage: "前端直接写入线性模组速度",
  },
  {
    key: "control.saveBindingData",
    name: TOPICS.control.saveBindingData,
    label: "保存绑扎数据",
    messageType: MESSAGE_TYPES.float32,
    sourceLayer: "control",
    sourceLabel: "控制层",
    ownerNode: "moduanNode",
    direction: "publish",
    usage: "前端直接触发末端数据保存",
  },
  {
    key: "tf.live",
    name: TOPICS.tf.live,
    label: "TF 动态树",
    messageType: MESSAGE_TYPES.tfMessage,
    sourceLayer: "tf",
    sourceLabel: "TF 层",
    ownerNode: "tf broadcasters",
    direction: "subscribe",
    usage: "三维坐标轴与实体位置",
  },
  {
    key: "tf.static",
    name: TOPICS.tf.static,
    label: "TF 静态树",
    messageType: MESSAGE_TYPES.tfMessage,
    sourceLayer: "tf",
    sourceLabel: "TF 层",
    ownerNode: "tf broadcasters",
    direction: "subscribe",
    usage: "三维坐标轴与实体位置",
  },
  {
    key: "tf.setCameraTcpExtrinsic",
    name: TOPICS.tf.setCameraTcpExtrinsic,
    label: "相机-TCP外参热更新",
    messageType: MESSAGE_TYPES.pose,
    sourceLayer: "tf",
    sourceLabel: "TF 层",
    ownerNode: "gripper_tf_broadcaster",
    direction: "publish",
    usage: "设置 Scepter_depth_frame -> gripper_frame 的 translation_mm",
  },
]);

const TOPIC_REGISTRY_BY_NAME = new Map(
  FRONTEND_DIRECT_TOPIC_REGISTRY.map((entry) => [entry.name, entry]),
);

const TOPIC_REGISTRY_BY_KEY = new Map(
  FRONTEND_DIRECT_TOPIC_REGISTRY.map((entry) => [entry.key, entry]),
);

const POINT_CLOUD_SOURCE_TOPIC_KEYS = Object.freeze({
  filteredWorldCoord: "camera.filteredWorldCoord",
  rawWorldCoord: "camera.rawWorldCoord",
});

export function getTopicRegistryEntry(topicName) {
  return TOPIC_REGISTRY_BY_NAME.get(topicName) || null;
}

export function getTopicRegistryEntryByKey(registryKey) {
  return TOPIC_REGISTRY_BY_KEY.get(registryKey) || null;
}

export function getTopicLayerSourceTopic(source) {
  const registryKey = POINT_CLOUD_SOURCE_TOPIC_KEYS[source] || POINT_CLOUD_SOURCE_TOPIC_KEYS.filteredWorldCoord;
  return getTopicRegistryEntryByKey(registryKey)?.name || TOPICS.camera.filteredWorldCoord;
}

export function getPointCloudTopicName(source) {
  return getTopicLayerSourceTopic(source);
}
