export const PROCESS_IMAGE_REQUEST_MODES = Object.freeze({
  DEFAULT: 0,
  ADAPTIVE_HEIGHT: 1,
  BIND_CHECK: 2,
  SCAN_ONLY: 3,
  EXECUTION_REFINE: 4,
});

export const FRONTEND_VISUAL_RECOGNITION_REQUEST_MODE = PROCESS_IMAGE_REQUEST_MODES.SCAN_ONLY;
export const FRONTEND_VISUAL_RECOGNITION_MODE_LABEL = "Surface-DP物理先验";
export const FRONTEND_VISUAL_RECOGNITION_FULL_LABEL = "Surface-DP物理先验扫描输出";
